name: gestion_vente_ultra
description: GESTION DE VENTE ULTRA - application de gestion commerciale (squelette Flutter)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  flutter_slidable: ^2.0.0
  intl: ^0.17.0
  uuid: ^3.0.6
  charts_flutter: ^0.12.0
  share_plus: ^4.0.10
  flutter_pdfview: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
